<?php

use Illuminate\Database\Seeder;

class MedicinesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('medicines')->insert([
            [
                'kon_medicine_id' => 'qon000000001',
                'bunkaren_code' => 1,
                'code' => '123456789012',
                'medicine_code' => 0,
                'receipt_computerized_processing1' => 0,
                'receipt_computerized_processing2' => 0,
                'popular_name' => 'アクタリット',
                'name' => 'アクタリット',
                'phonetic' => 'アクタリット',
                'standard_unit' => '錠剤100mg 1錠',
                'package_presentation' => 'SW-ACT',
                'unit' => '錠',
                'drug_price_equivalent' => 1,
                'maker_id' => '1',
                'selling_agency_code' => '1',
                'medicine_effet_id' => 0,
                'dosage_type_division' => 0,
                'transitional_deadline' => 0,
                'danger_poison_category1' => 0,
                'danger_poison_category2' => 0,
                'danger_poison_category3' => 0,
                'danger_poison_category4' => 0,
                'danger_poison_category5' => 0,
                'prescription_drug_category' => 0,
                'biological_product_classification' => 0,
                'generic_product_flag' => true,
                'production_stop_date' => '2019-12-31',
                'discontinuation_date' => '2019-12-31',
                'hospital_code' => 0,
                'owner_classification' => 1,
                'search' => 'アクタリット',
                'creater' => 0,
                'updater' => 0,
                'deleter' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kon_medicine_id' => 'qon000000002',
                'bunkaren_code' => 2,
                'code' => '123456789012',
                'medicine_code' => 0,
                'receipt_computerized_processing1' => 0,
                'receipt_computerized_processing2' => 0,
                'popular_name' => 'イミダプリル塩酸塩',
                'name' => 'イミダプリル塩酸塩',
                'phonetic' => 'イミダプリルエンサンエン',
                'standard_unit' => '錠剤5mg 1錠',
                'package_presentation' => 'SW-ACT',
                'unit' => '錠',
                'drug_price_equivalent' => 1,
                'maker_id' => '1',
                'selling_agency_code' => '1',
                'medicine_effet_id' => 0,
                'dosage_type_division' => 0,
                'transitional_deadline' => 0,
                'danger_poison_category1' => 0,
                'danger_poison_category2' => 0,
                'danger_poison_category3' => 0,
                'danger_poison_category4' => 0,
                'danger_poison_category5' => 0,
                'prescription_drug_category' => 0,
                'biological_product_classification' => 0,
                'generic_product_flag' => true,
                'production_stop_date' => '2019-12-31',
                'discontinuation_date' => '2019-12-31',
                'hospital_code' => 0,
                'owner_classification' => 1,
                'search' => 'イミダプリル塩酸塩',
                'creater' => 0,
                'updater' => 0,
                'deleter' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kon_medicine_id' => 'qon000000003',
                'bunkaren_code' => 3,
                'code' => '123456789012',
                'medicine_code' => 0,
                'receipt_computerized_processing1' => 0,
                'receipt_computerized_processing2' => 0,
                'popular_name' => 'エンテカビルOD',
                'name' => 'エンテカビルOD',
                'phonetic' => 'エンテカビルオーディー',
                'standard_unit' => '錠剤0.5mg 1錠',
                'package_presentation' => 'SW-ACT',
                'unit' => '錠',
                'drug_price_equivalent' => 1,
                'maker_id' => '2',
                'selling_agency_code' => '1',
                'medicine_effet_id' => 0,
                'dosage_type_division' => 0,
                'transitional_deadline' => 0,
                'danger_poison_category1' => 0,
                'danger_poison_category2' => 0,
                'danger_poison_category3' => 0,
                'danger_poison_category4' => 0,
                'danger_poison_category5' => 0,
                'prescription_drug_category' => 0,
                'biological_product_classification' => 0,
                'generic_product_flag' => true,
                'production_stop_date' => '2019-12-31',
                'discontinuation_date' => '2019-12-31',
                'hospital_code' => 0,
                'owner_classification' => 1,
                'search' => 'エンテカビルOD',
                'creater' => 0,
                'updater' => 0,
                'deleter' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'kon_medicine_id' => 'qon000000004',
                'bunkaren_code' => 4,
                'code' => '123456789012',
                'medicine_code' => 0,
                'receipt_computerized_processing1' => 0,
                'receipt_computerized_processing2' => 0,
                'popular_name' => 'スマトリプタン内用液',
                'name' => 'スマトリプタン内用液',
                'phonetic' => 'スマトリプタンナイヨウエキ',
                'standard_unit' => '液剤50mg2mL 1包',
                'package_presentation' => 'SW-ACT',
                'unit' => '包',
                'drug_price_equivalent' => 1,
                'maker_id' => '2',
                'selling_agency_code' => '1',
                'medicine_effet_id' => 0,
                'dosage_type_division' => 0,
                'transitional_deadline' => 0,
                'danger_poison_category1' => 0,
                'danger_poison_category2' => 0,
                'danger_poison_category3' => 0,
                'danger_poison_category4' => 0,
                'danger_poison_category5' => 0,
                'prescription_drug_category' => 0,
                'biological_product_classification' => 0,
                'generic_product_flag' => true,
                'production_stop_date' => '2019-12-31',
                'discontinuation_date' => '2019-12-31',
                'hospital_code' => 0,
                'owner_classification' => 1,
                'search' => 'スマトリプタン内用液',
                'creater' => 0,
                'updater' => 0,
                'deleter' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),

            ],
            [
                'kon_medicine_id' => 'qon000000005',
                'bunkaren_code' => 5,
                'code' => '123456789012',
                'medicine_code' => 0,
                'receipt_computerized_processing1' => 0,
                'receipt_computerized_processing2' => 0,
                'popular_name' => 'セレスタミン配合錠',
                'name' => 'セレスタミン配合錠',
                'phonetic' => 'セレスタミンハイゴウジョウ',
                'standard_unit' => '錠剤 1錠',
                'package_presentation' => 'SW-ACT',
                'unit' => '錠',
                'drug_price_equivalent' => 1,
                'maker_id' => '2',
                'selling_agency_code' => '1',
                'medicine_effet_id' => 0,
                'dosage_type_division' => 0,
                'transitional_deadline' => 0,
                'danger_poison_category1' => 0,
                'danger_poison_category2' => 0,
                'danger_poison_category3' => 0,
                'danger_poison_category4' => 0,
                'danger_poison_category5' => 0,
                'prescription_drug_category' => 0,
                'biological_product_classification' => 0,
                'generic_product_flag' => true,
                'production_stop_date' => '2019-12-31',
                'discontinuation_date' => '2019-12-31',
                'hospital_code' => 0,
                'owner_classification' => 1,
                'search' => 'セレスタミン配合錠',
                'creater' => 0,
                'updater' => 0,
                'deleter' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
